Repository youstanzr/YouTag, pull requests merged in 2020-05, with the labels that each got.

#45 Thumbnail from gallery + UI improvements
  YouTag/LibraryCell.swift
  YouTag/LocalFilesManager.swift
  YouTag/NowPlayingView.swift
  YouTag/SongDetailViewController.swift
  YouTag/ViewController.swift
Labels: enhancement

#47 Fix empty library issue
  YouTag/PlaylistManager.swift
  YouTag/YYTAudioPlayer.swift
Labels: bug, tidy

#54 Change file name
  YouTag.xcodeproj/project.pbxproj
  YouTagTests/YouTagTests.swift
  YouTagUITests/YouTagUITests.swift
Labels: tidy

#55 Change YYTFilterTagView Initializer
  YouTag/ViewController.swift
  YouTag/YYTFilterTagView.swift
Labels: tidy

#63 Update Alamofire Swift Package
  YouTag.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: dependency update

#67 Code refactor and cleanup
  YouTag.xcodeproj/project.pbxproj
  YouTag.xcodeproj/xcshareddata/xcschemes/YouTag.xcscheme
  YouTag/Extensions.swift
  YouTag/Info.plist
  YouTag/ViewController.swift
Labels: tidy

#68 Update Swift Package + Add gitignore
  .gitignore
  YouTag.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  YouTag.xcodeproj/xcshareddata/xcschemes/YouTag.xcscheme
  YouTag.xcodeproj/xcuserdata/Youstanzr.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  YouTag.xcodeproj/xcuserdata/Youstanzr.xcuserdatad/xcschemes/xcschememanagement.plist
  YouTag/YouTag.xcdatamodeld/.xccurrentversion
  YouTag/YouTag.xcdatamodeld/YouTag.xcdatamodel/contents
Labels: dependency update, tidy

#53 Implemented Tags Suggestion Feature
  YouTag.xcodeproj/project.pbxproj
  YouTag/FilterPickerView.swift
  YouTag/SearchTextField.swift
  YouTag/SongDetailViewController.swift
  YouTag/ViewController.swift
  YouTag/YYTFilterTagView.swift
  YouTag/YYTTagCell.swift
  YouTag/YYTTagView.swift
Labels: enhancement

#69 Enhance suggestions UI & UX + update gitignore
  .gitignore
  README.md
  YouTag.xcodeproj/project.pbxproj
  YouTag.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  YouTag.xcodeproj/project.xcworkspace/xcuserdata/Youstanzr.xcuserdatad/IDEFindNavigatorScopes.plist
  YouTag.xcodeproj/project.xcworkspace/xcuserdata/Youstanzr.xcuserdatad/WorkspaceSettings.xcsettings
  YouTag/AppDelegate.swift
  YouTag/SongDetailViewController.swift
  YouTag/YYTTagCell.swift
  YouTag/YYTTagView.swift
Labels: enhancement
